draw_config:
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: auto
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: true
  key_side_pars:
    rel_x: 0
    rel_y: 4
    rel_w: 12
    rel_h: 12
    rx: 4
    ry: 4
  svg_extra_style: |
    .key rect {
      stroke: black;
      stroke-width: 0.7pt;
    }

  footer_text: Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map: {}
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ▽
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: true
  modifier_fn_map:
    left_ctrl: Ctl
    right_ctrl: Ctl
    left_shift: ⇧
    right_shift: ⇧
    left_alt: Alt
    right_alt: AltGr
    left_gui: Win
    right_gui: Win
    keycode_combiner: '{mods}+{key}'
    mod_combiner: '{mod_1}+{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  zmk_remove_keycode_prefix: [ "DE_" ]
  zmk_keycode_map:
    BACKSPACE: '$$mdi:backspace-outline$$'
    BSPC: '$$mdi:backspace-outline$$'
    DELETE: '$$mdi:backspace-reverse-outline$$'
    DEL: '$$mdi:backspace-reverse-outline$$'
    SPACE: '$$mdi:keyboard-space$$'
    CAPS: '$$mdi:caps-lock$$'
    ENTER: '↵'
    TAB: '⇥'
    LSHFT: '$$mdi:apple-keyboard-shift$$'
    RSHFT: '$$mdi:apple-keyboard-shift$$'
    A_UMLAUT: Ä
    O_UMLAUT: Ö
    U_UMLAUT: Ü
    ESZETT: ß
    EXCLAMATION: '!'
    '&mmv MOVE_RIGHT': '🖰 ⇢'
    '&mmv MOVE_LEFT': '🖰 ⇠'
    '&mmv MOVE_UP': '🖰 ⇡'
    '&mmv MOVE_DOWN': '🖰 ⇣'
    '&msc SCRL_UP': '🖱 ⇑'
    '&msc SCRL_DOWN': '🖱 ⇓'
    '&msc SCRL_LEFT': '🖱 ⇐'
    '&msc SCRL_RIGHT': '🖱 ⇒'
    '&mkp LCLC': '🖱 L'
    '&mkp RCLC': '🖱 R'
    '&mkp MCLC': '🖱 M'
    PRINTSCREEN: PrScr
    EURO: '€'
    ACUTE: '´'
    KP_NUM: Num Lock
    KP_N0: '0'
    KP_N1: '1'
    KP_N2: '2'
    KP_N3: '3'
    KP_N4: '4'
    KP_N5: '5'
    KP_N6: '6'
    KP_N7: '7'
    KP_N8: '8'
    KP_N9: '9'
    KP_DOT: ','
    KP_COMMA: ','
    KP_ENTER: '↵'
    KP_PLUS: '+'
    KP_SUBTRACT: '-'
    KP_ASTERISK: '*'
    KP_DIVIDE: '/'
    BT_SEL: 'ᛒ'
    BT_CLR: 'ᛒ✕'

    UP: '$$mdi:arrow-up-thin$$'
    DOWN: '$$mdi:arrow-down-thin$$'
    LEFT: '$$mdi:arrow-left-thin$$'
    RIGHT: '$$mdi:arrow-right-thin$$'

    LALT: Alt
    RALT: AltGr
    LCTRL: Ctrl
    RCTRL: Ctrl
    LGUI: '$$mdi:microsoft-windows$$'
    RGUI: '$$mdi:microsoft-windows$$'

    '&bootloader': '$$mdi:alpha-b-box-outline$$'

    PAGE_UP: PgUp
    PG_UP: PgUp
    PAGE_DOWN: PgDn
    PG_DN: PgDn
    INSERT: Ins
    INS: Ins
    HOME: Home
    END: End
    ESCAPE: ESC
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
  zmk_combos: {}
  zmk_preamble: '#define KEYMAP_DRAWER'
  zmk_additional_includes: []
